syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "core/headers.proto";

package onboarding;

option go_package = "Rinnegan/proto-generated/protos-frontend/onboarding";

message TriggerPhoneOTPVerificationRequest {
  core.RequestHeader req_header = 1;
  string otp = 2;
}

message TriggerEmailVerificationRequest {
  core.RequestHeader req_header = 1;
  string email_id = 2;
  string user_name = 3;
}

message TriggerPanVerificationRequest {
  core.RequestHeader req_header = 1;
  string pan_number = 2;
  google.protobuf.Timestamp date_of_birth = 3;
}

message TriggerLivenessCheckRequest {
  core.RequestHeader req_header = 1;
  string otp_spoken = 2;
}

// Define the Aadhar verification request message
message AadharVerificationRequest {
  core.RequestHeader req_header = 1;
  string aadhar_number = 2;
  string otp = 3;
}