syntax = "proto3";
import "protos-frontend/screens/onboarding_screen_options.proto";

package deeplink;

option go_package = "Rinnegan/proto-generated/protos-frontend/deeplink";

message OnboardingPodDeeplink {
  oneof Screen {
    screens.OtherConsentsScreen other_consent_screen = 1;
    screens.BiometricConsentScreen biometric_consent_screen = 2;
    screens.LivenessCheckScreen liveness_check_screen = 3;
    screens.PanVerificationScreen pan_verification_screen = 4;
    screens.PhoneVerificationScreen phone_verification_screen = 5;
    screens.PhoneOTPScreen phone_otp_screen = 6;
    screens.EmailVerificationScreen email_verification_screen = 7;
    screens.TermsConditionsScreen terms_conditions_screen=8;
  }
}
